[build]
  command = "npm run build"
  publish = "build/"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    # Enable HTTP2 Server Push on the specified file types.
    # You can also set this to "*" to enable it for all file types.
    Link = '''
      </static/css/styles.chunk.css>; rel=preload; as=style
      </static/js/main.chunk.js>; rel=preload; as=script
      </static/js/0.chunk.js>; rel=preload; as=script
      </static/js/bundle.js>; rel=preload; as=script
    '''
